services:
  nest-ea:
    container_name: nest-ea${DATE_TAG} #设置容器名称
    image: nest-ea:${DATE_TAG}  # 使用在构建时设置的日期标签
    build:
      context: .  # 构建上下文，通常是当前目录
      dockerfile: Dockerfile  # Dockerfile 文件的位置
    ports:
      - "3002:3002"  # 映射宿主机的 3002 端口到容器的 3002 端口
    volumes:
      - .:/nest-ea  # 将当前目录挂载到容器的 /nest-ea 目录中，方便实时更新代码
    environment:
      - NODE_ENV=prod  # 设置环境变量，表示运行在生产环境
    restart: unless-stopped  # 容器崩溃后自动重启
    networks:
      - nest-network  # 定义服务使用的网络

networks:
  nest-network:
    driver: bridge  # 使用桥接网络模式
