services:
  nest-ea:
    build:
      context: .  # 构建上下文，通常是当前目录
      dockerfile: Dockerfile  # Dockerfile 文件的位置
    ports:
      - "3002:3002"  # 映射宿主机的 3002 端口到容器的 3002 端口
    volumes:
      - .:/nest-ea  # 将当前目录挂载到容器的 /nest-ea 目录中，方便实时更新代码
    environment:
      - NODE_ENV=production  # 设置环境变量，表示运行在生产环境
    restart: always  # 容器崩溃后自动重启
    networks:
      - nest-ea-network  # 定义服务使用的网络

networks:
  nest-ea-network:
    driver: bridge  # 使用桥接网络模式
