services:
  nest-ea:
    container_name: nest-ea${DATE_TAG} #设置容器名称
    image: nest-ea:${DATE_TAG}  # 使用在构建时设置的日期标签
    build:
      context: . # 构建上下文，通常是当前目录
      dockerfile: Dockerfile # Dockerfile 文件的位置
    ports:
      - '3002:3002' # 映射宿主机的 3002 端口到容器的 3002 端口
    environment:
      - NODE_ENV=prod # 设置环境变量，表示运行在生产环境
    networks:
      - network # 定义服务使用的网络
    restart: always # 设置容器重启策略，确保容器被自动重启
networks:
  network:
    driver: bridge # 使用桥接网络模式
