@BASE_URL = http://localhost:3002
 @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QwMDIiLCJpZCI6NiwiYXBwSWQiOiJXRUJfQURNSU4iLCJyb2xlcyI6WyIyIl0sImlhdCI6MTc2NzU4OTkwMSwiZXhwIjoxNzY3Njc2MzAxfQ.F1FV7uky_LPsd2E_gJSJLXieCMsX7vL37Copy7mfqIE
@token2 = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3QwMDIiLCJpZCI6NiwiYXBwSWQiOiJXRUJfQURNSU4iLCJyb2xlcyI6WyIyIl0sImlhdCI6MTc2NjM5MjQ2NSwiZXhwIjoxNzY2NDc4ODY1fQ.4-hsejjKxKcU_FTVZrxouN0V-rJ3uCTEUr1-jyLAwxI

###
POST {{BASE_URL}}/user/login
Content-Type: application/json
x-app-id: WEB_ADMIN

{
    "username": "test002",
    "password": "123456"
}

###
POST {{BASE_URL}}/user/register
Content-Type: application/json
x-app-id: WEB_ADMIN

{
    "username": "test001",
    "password": "123456"
}

###
GET  {{BASE_URL}}/user/user_list
Content-Type: application/json
Authorization: Bearer {{token}}
x-app-id: WEB_ADMIN

###
GET  {{BASE_URL}}/user/6
Content-Type: application/json
Authorization: Bearer {{token}}
x-app-id: WEB_ADMIN

###
GET  {{BASE_URL}}/api/time
Content-Type: application/json
Authorization: Bearer {{token}}
x-app-id: WEB_ADMIN

###
POST {{BASE_URL}}/mail/send_to_user
Content-Type: application/json
Authorization: Bearer {{token2}}
x-app-id: WEB_ADMIN

{
    "subject": "test_mail",
    "content": "1234阿斯顿噶发啊手动阀as56",
    "userId": 5
}