name: Deploy to Aliyun Docker

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to server
      run: |
        ssh user@101.200.160.131 'cd ~/deploy/nest-ea/ && docker-compose up -d'
    - name: Deploy Docker containers
      run: |
        ssh user@101.200.160.131 << 'EOF'
          cd ~/deploy/nest-ea/
          docker-compose down
          docker-compose up --build -d
        EOF 
